# Generated by Django 5.2.14 on 2026-05-11 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('secret_hash', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_rpm', models.PositiveIntegerField(default=120)),
                ('requests_count', models.BigIntegerField(default=0)),
                ('prompt_tokens_total', models.BigIntegerField(default=0)),
                ('completion_tokens_total', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIKeyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('api_key_public_id', models.CharField(blank=True, default='', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api_keys.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'revoked_at'], name='api_keys_ap_user_id_fa4b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyauditlog',
            index=models.Index(fields=['created_at'], name='api_keys_ap_created_94886b_idx'),
        ),
    ]
