# Generated by Django 5.2.14 on 2026-05-11 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_request_limit', models.PositiveIntegerField(blank=True, help_text='If set, caps successful inference requests per UTC day (session UI path).', null=True)),
                ('daily_token_limit', models.PositiveIntegerField(blank=True, help_text='If set, caps completion-token estimates per UTC day (session UI path).', null=True)),
                ('default_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_profiles', to='api_keys.apikey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
