# Generated by Django 6.0.5 on 2026-05-25 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('market_research', 'Market Research'), ('job_discovery', 'Job Discovery')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('search_query', models.CharField(blank=True, default='', max_length=1024)),
                ('schedule_cron', models.CharField(blank=True, default='', max_length=255)),
                ('digest_frequency', models.CharField(choices=[('disabled', 'Disabled'), ('real_time', 'Real Time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='disabled', max_length=20)),
                ('llm_backend_preference', models.CharField(choices=[('llamacpp', 'llama.cpp'), ('vllm', 'vLLM')], default='llamacpp', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('max_results', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('bot_token', models.CharField(blank=True, default='', max_length=512)),
                ('chat_id', models.CharField(blank=True, default='', max_length=128)),
                ('digest_enabled', models.BooleanField(default=True)),
                ('digest_schedule', models.CharField(default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
                'verbose_name_plural': 'Telegram Configurations',
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='running', max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('discovered_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_logs', models.JSONField(blank=True, default=list)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('url', models.URLField(blank=True, default='', max_length=2048)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('semantic_hash', models.CharField(blank=True, default='', max_length=64)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='agents.agent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='agents.agentrun')),
            ],
            options={
                'verbose_name': 'Agent Result',
                'verbose_name_plural': 'Agent Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', '-created_at'], name='agents_agen_agent_i_5535d1_idx'), models.Index(fields=['semantic_hash'], name='agents_agen_semanti_c3d917_idx')],
            },
        ),
    ]
