# Generated by Django 5.2.14 on 2026-05-11 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(max_length=256)),
                ('stream', models.BooleanField(default=False)),
                ('status_code', models.PositiveIntegerField()),
                ('latency_ms', models.PositiveIntegerField()),
                ('stream_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ttft_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_char_length', models.PositiveIntegerField(default=0)),
                ('prompt_token_estimate', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('preview', models.CharField(blank=True, default='', max_length=100)),
                ('full_prompt', models.TextField(blank=True, default='')),
                ('error_kind', models.CharField(blank=True, default='', max_length=64)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_logs', to='api_keys.apikey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='inference_i_created_f7d48d_idx'), models.Index(fields=['user', 'created_at'], name='inference_i_user_id_c5333a_idx'), models.Index(fields=['api_key', 'created_at'], name='inference_i_api_key_23a044_idx')],
            },
        ),
    ]
